import MHLocalizedStrings from '../CommonModules/LocalizedStrings';
import IntlMessageFormat from 'intl-messageformat';
import 'intl';
import 'intl/locale-data/jsonp/en.js';
import 'intl/locale-data/jsonp/zh-Hans.js';
import 'intl/locale-data/jsonp/zh-Hant.js';
import 'intl/locale-data/jsonp/ko-KR.js';
export const strings = {
  "en":{
    string_is_loading:"Loading…",
    setting:"setting",
    featureSetting:"Shortcut settings",
    commonSetting:"Common settings",
    deviceName:"Device name",
    feedback:"feedback",
    locationManagement:"Locations",
    shareDevice:"Share device",
    ifttt:"Automation",
    firmwareUpgrate:"Check for firmware updates",
    moreSetting:"Additional settings",
    addToDesktop:"Add to Home screen",
    resetDevice:"Remove device",
    licenseAndPolicy:"User Agreement & Privacy Policy",
    ir_main_copy:'Duplicate remote',
    ir_main_add:'Add remote',
    ir_device_type_tv_text:'TV',
    ir_device_type_box_text:'TV Box',
    ir_device_type_air_conditioner_text:'Air conditioner',
    ir_device_type_fan_text:'Fan',
    ir_device_type_set_top_box_text:'Set-top box',
    ir_device_type_purifier_text:'Set-top box',
    ir_device_type_dvd_text:'DVD player',
    ir_device_type_iptv_box_text:'IPTV set-top box',
    ir_device_type_projector_text:'Projector',
    ir_device_type_lamp:'Smart lamp',
    ir_device_type_mi_controller:'Mi Remote',
    ir_device_type_camera:'Camera',
    ir_device_type_amplifier:'Speaker',
    ir_device_type_water_heater:'Water heater',
    ir_device_type_water_unknown:'Mi Home general devices',
    ir_device_type_unknown:'Customize',
    get_way_choose_tips_title:'Please select one IR gateway to control device',
    ir_controller_power_text:'Switch',
    ir_controller_power_on_text:'On',
    ir_controller_power_off_text:'Of',
    ir_controller_mode_text:'Mode',
    ir_controller_sleep_text:'Sleep',
    ir_controller_temp_up_text:'Temperature+',
    ir_controller_temp_down_text:'Temperature-',
    ir_controller_heating_text:'Heating',
    ir_controller_cool_text:'Cooling',
    ir_controller_temp_text:'Adjust',
    ir_controller_comfort_text:'Other buttons',
    wind_speed:'Wind speed',
    wind_speed_auto:'Auto',
    ir_wind_low:'Low',
    ir_wind_mid:'Medium',
    ir_wind_high:'High',
    ac_mode_dry:'Dehumidifying',
    ac_mode_fan:'Venting',
    timer:'Timer',
    wind_sweep:'Swing',
    wind_speed:'Wind speed',
    wind_direct:'Wind direction',
    ir_controller_wind_class_text:'Wind type',
    extra_key_text:'Extension',
    ir_controller_back_text:'Back',
    match_ac_power:'Power',
    search_device:'Search brand',
    search_keyword_text:'Search keyword',
    get_way_choose_tips_title:'Please select one IR gateway to control device',
    ir_match_set_top_box:'Select mobile carrier',
    ir_match_location_format:'Location: ',
    ir_add_ic_description:'Device needs time to respond\nPlease give it a few minutes',
    ir_confirm_button_description_font:'Press remote button toward ',
    ir_confirm_button_description_after:'Press remote button toward ',
    ir_confirm_button_confirm:'Then confirm if',
    ir_confirm_button_response:'s responds',
    ir_add_ic_test_btn_num:'Test buttons',
    ir_single_match_failed:'Pairing failed, please try ',
    extra_key_text:'Extension',
    ir_take_look:'Take a look',
    ir_take_look_desc:'No IR gateway available',
    ir_trun_off_air:'Turn off AC',
    ir_trun_on_air:'Turn on AC',
    ir_trunon_air_special:'Turn on AC and set to designated status',
    device_is_response:'Did the device respond?',
    match_ok_button:'Yes',
    match_cancel_button:'No',
    ir_led_switch:'Instruction light',
    ios_sting_3:'Loading...',
    ios_sting_4:'Seeting Up...',
    ios_sting_5:'Indicator Settings',
    ir_setting:'Remote settings',
    brand_list:'Brand list',
    set_top_box_list:'Set-top Box List',
    ir_add_ic_title_name:'Add remote',
    ir_matching_controller:'Pair remote',
    ir_study_controller_title:'Duplicate remote',
    ir_matching_success:'Finished',
    ir_device_customer:'Customize remote',
    ir_study_add_btn_text:'Add key',
    ir_toast_version:'Master remote control version:',
    agreement_title:"User Agreement",
    policy_title:"Privacy Policy",
    A03_greement_url:require('../Resources/en_a03_agreement.html'),
    A03_policy_url:require('../Resources/en_a03_policy.html'),
    B01_greement_url:require('../Resources/en_b01_agreement.html'),
    B01_policy_url:require('../Resources/en_b01_policy.html'),
    V2_greement_url:require('../Resources/en_remote_v2_agreement.html'),
    V2_policy_url:require('../Resources/en_remote_v2_policy.html'),
    ir_toast_key_read_timeout:'Timed out, please try again',
    ir_toast_key_send_failed:'Sorry, failed to send',
    ir_toast_key_read_other_error:'An error occurred, please try again',
    ir_toast_get_data_failed:'Failed to obtain data, please keep network connected',
    ir_device_offline:'(Device off-line)',
    ir_device_share:'(Share Device)',
    ir_search_list:'Search List',
    ir_not_learn_text:'Air conditioning has no learning function',
    match_first_control_text:'The first remote controller has come to the front',
    match_last_control_text:'To the last remote control',
    match_remoter_press_text:'Press the same button on the remote control center',
    sence_temp_text:'Temperature',
    sence_mode_text:'Model',
    sence_speed_text:'Wind speed',
    ir_cancel:'Cancel',
    ir_confirm:'OK',
    ir_controller_edit_key_name_title:'Button name',
    ir_input_placeholder_text:'Please enter button name',
    edit_save_failed_no_keys:'No button learned',
    ir_controller_others_already_studied:'Already learned',
    ir_gateWay_list:'Gateway list',
    ir_device_type_no_learn:'This type has no learning function',
    ir_delete:'delete',
    ir_delete_device_text:'Are you sure you want to delete the device?',
    list_select_area:'Select region',
    customer_fun:'custom',
    main_add_desc:'Follow the instructions, and control through a few simple trials',
    ir_main_copy_desc:'Duplicate every command on the buttons of the remote to control',
  },
  "zh":{
    string_is_loading:"加载中…",
    setting:"设置",
    featureSetting:"功能设置",
    commonSetting:"通用设置",
    deviceName:"设备名称",
    locationManagement:"位置管理",
    shareDevice:"设备共享",
    ifttt:"智能",
    feedback:"反馈",
    firmwareUpgrate:"检查固件升级",
    moreSetting:"更多设置",
    addToDesktop:"添加到桌面",
    resetDevice:"删除设备",
    licenseAndPolicy:"使用条款和隐私政策",
    ir_main_copy:'复制遥控器',
    ir_main_add:'添加遥控器',
    ir_device_type_tv_text:'电视',
    ir_device_type_box_text:'盒子',
    ir_device_type_air_conditioner_text:'空调',
    ir_device_type_fan_text:'风扇',
    ir_device_type_set_top_box_text:'机顶盒',
    ir_device_type_purifier_text:'空气净化器',
    ir_device_type_dvd_text:'DVD播放器',
    ir_device_type_iptv_box_text:'IPTV机顶盒',
    ir_device_type_projector_text:'投影仪',
    ir_device_type_lamp:'智能灯',
    ir_device_type_mi_controller:'小米遥控器',
    ir_device_type_camera:'照相机',
    ir_device_type_amplifier:'音响',
    ir_device_type_water_heater:'热水器',
    ir_device_type_water_unknown:'米家通用设备',
    ir_device_type_unknown:'自定义',
    get_way_choose_tips_title:'请选择用来控制设备的红外网关',
    ir_controller_power_text:'开关',
    ir_controller_power_on_text:'开',
    ir_controller_power_off_text:'关',
    ir_controller_mode_text:'模式',
    ir_controller_sleep_text:'睡眠',
    ir_controller_temp_up_text:'温度+',
    ir_controller_temp_down_text:'温度-',
    ir_controller_heating_text:'制热',
    ir_controller_cool_text:'制冷',
    ir_controller_temp_text:'调整',
    ir_controller_comfort_text:'其他按键',
    wind_speed:'风速',
    wind_speed_auto:'自动',
    ir_wind_low:'低速',
    ir_wind_mid:'中速',
    ir_wind_high:'高速',
    ac_mode_dry:'除湿',
    ac_mode_fan:'通风',
    timer:'定时',
    wind_sweep:'扫风',
    wind_speed:'风速',
    wind_direct:'风向',
    ir_controller_wind_class_text:'风类',
    extra_key_text:'扩展键',
    ir_controller_back_text:'返回',
    match_ac_power:'电源',
    search_device:'搜索品牌',
    search_keyword_text:'搜索关键字',
    get_way_choose_tips_title:'请选择用来控制设备的红外网关',
    ir_match_set_top_box:'运营商选择',
    ir_match_location_format:'所在地: ',
    ir_add_ic_description:'设备需要时间来响应您的操作,\n还请您操作后适当等待一下',
    ir_confirm_button_description_font:'请对准',
    ir_confirm_button_description_after:'点击遥控按钮',
    ir_confirm_button_confirm:'然后确认',
    ir_confirm_button_response:'是否响应',
    ir_add_ic_test_btn_num:'测试按键',
    ir_single_match_failed:'匹配失败,请尝试自定义学习遥控器功能',
    extra_key_text:'扩展键',
    ir_take_look:'立即去看看',
    ir_take_look_desc:'您还没有红外网关哦～',
    ir_trun_off_air:'关空调',
    ir_trun_on_air:'开空调',
    ir_trunon_air_special:'开空调并调整至指定状态',
    device_is_response:'设备是否有响应?',
    match_ok_button:'是',
    match_cancel_button:'否',
    ir_led_switch:'指示灯',
    ios_sting_3:'加载中...',
    ios_sting_4:'设置中...',
    ios_sting_5:'指示灯设置',
    ir_setting:'遥控器设置',
    brand_list:'品牌列表',
    set_top_box_list:'机顶盒列表',
    ir_add_ic_title_name:'添加遥控器',
    ir_matching_controller:'匹配遥控器',
    ir_study_controller_title:'复制遥控器',
    ir_matching_success:'完成',
    ir_device_customer:'自定义遥控器',
    ir_study_add_btn_text:'添加按键',
    ir_toast_version:'万能遥控器版本号:',
    agreement_title:"用户协议",
    policy_title:"隐私条款",
    A03_greement_url:require('../Resources/a03_agreement.html'),
    A03_policy_url:require('../Resources/a03_policy.html'),
    B01_greement_url:require('../Resources/b01_agreement.html'),
    B01_policy_url:require('../Resources/b01_policy.html'),
    V2_greement_url:require('../Resources/remote_v2_agreement.html'),
    V2_policy_url:require('../Resources/remote_v2_policy.html'),
    ir_toast_key_read_timeout:'抱歉，超时了，请重试！',
    ir_toast_key_send_failed:'抱歉，发送失败了！',
    ir_toast_key_read_other_error:'抱歉，出错了，请重试！',
    ir_toast_get_data_failed:'获取数据失败，请保持网络畅通！',
    ir_device_offline:'(设备离线)',
    ir_device_share:'(分享设备)',
    ir_search_list:'搜索列表',
    ir_not_learn_text:'空调暂未开通学习功能',
    match_first_control_text:'已经到最前面一套遥控器',
    match_last_control_text:'已经到最后一套遥控器',
    match_remoter_press_text:'对准遥控器中心按下相同按键',
    sence_temp_text:'温度',
    sence_mode_text:'模式',
    sence_speed_text:'风速',
    ir_cancel:'取消',
    ir_confirm:'确定',
    ir_controller_edit_key_name_title:'按键名称',
    ir_input_placeholder_text:'请输入按钮名称',
    edit_save_failed_no_keys:'并未学习任何按键!',
    ir_controller_others_already_studied:'已经学习',
    ir_gateWay_list:'网关列表',
    ir_device_type_no_learn:'该品类 - 未开通学习功能',
    ir_delete:'删除',
    ir_delete_device_text:'确定要删除该设备吗?',
    list_select_area:'选择区域',
    customer_fun:'自定义功能',
    main_add_desc:'跟随引导，通过简单的使用尝试，实现控制',
    ir_main_copy_desc:'对遥控器上的按键命令逐一复制，实现控制',
  },
  "zh-hk":{
   string_is_loading:"Loading…",
   setting:"setting",
   featureSetting:"Shortcut settings",
   commonSetting:"Common settings",
   deviceName:"Device name",
   feedback:"feedback",
   locationManagement:"Locations",
   shareDevice:"Share device",
   ifttt:"Automation",
   firmwareUpgrate:"Check for firmware updates",
   moreSetting:"Additional settings",
   addToDesktop:"Add to Home screen",
   resetDevice:"Remove device",
   licenseAndPolicy:"User Agreement & Privacy Policy",
   ir_main_copy:'Duplicate remote',
   ir_main_add:'Add remote',
   ir_device_type_tv_text:'TV',
   ir_device_type_box_text:'TV Box',
   ir_device_type_air_conditioner_text:'Air conditioner',
   ir_device_type_fan_text:'Fan',
   ir_device_type_set_top_box_text:'Set-top box',
   ir_device_type_purifier_text:'Set-top box',
   ir_device_type_dvd_text:'DVD player',
   ir_device_type_iptv_box_text:'IPTV set-top box',
   ir_device_type_projector_text:'Projector',
   ir_device_type_lamp:'Smart lamp',
   ir_device_type_mi_controller:'Mi Remote',
   ir_device_type_camera:'Camera',
   ir_device_type_amplifier:'Speaker',
   ir_device_type_water_heater:'Water heater',
   ir_device_type_water_unknown:'Mi Home general devices',
   ir_device_type_unknown:'Customize',
   get_way_choose_tips_title:'Please select one IR gateway to control device',
   ir_controller_power_text:'Switch',
   ir_controller_power_on_text:'On',
   ir_controller_power_off_text:'Of',
   ir_controller_mode_text:'Mode',
   ir_controller_sleep_text:'Sleep',
   ir_controller_temp_up_text:'Temperature+',
   ir_controller_temp_down_text:'Temperature-',
   ir_controller_heating_text:'Heating',
   ir_controller_cool_text:'Cooling',
   ir_controller_temp_text:'Adjust',
   ir_controller_comfort_text:'Other buttons',
   wind_speed:'Wind speed',
   wind_speed_auto:'Auto',
   ir_wind_low:'Low',
   ir_wind_mid:'Medium',
   ir_wind_high:'High',
   ac_mode_dry:'Dehumidifying',
   ac_mode_fan:'Venting',
   timer:'Timer',
   wind_sweep:'Swing',
   wind_speed:'Wind speed',
   wind_direct:'Wind direction',
   ir_controller_wind_class_text:'Wind type',
   extra_key_text:'Extension',
   ir_controller_back_text:'Back',
   match_ac_power:'Power',
   search_device:'Search brand',
   search_keyword_text:'Search keyword',
   get_way_choose_tips_title:'Please select one IR gateway to control device',
   ir_match_set_top_box:'Select mobile carrier',
   ir_match_location_format:'Location: ',
   ir_add_ic_description:'Device needs time to respond\nPlease give it a few minutes',
   ir_confirm_button_description_font:'Press remote button toward ',
   ir_confirm_button_description_after:'Press remote button toward ',
   ir_confirm_button_confirm:'Then confirm if',
   ir_confirm_button_response:'s responds',
   ir_add_ic_test_btn_num:'Test buttons',
   ir_single_match_failed:'Pairing failed, please try ',
   extra_key_text:'Extension',
   ir_take_look:'Take a look',
   ir_take_look_desc:'No IR gateway available',
   ir_trun_off_air:'Turn off AC',
   ir_trun_on_air:'Turn on AC',
   ir_trunon_air_special:'Turn on AC and set to designated status',
   device_is_response:'Did the device respond?',
   match_ok_button:'Yes',
   match_cancel_button:'No',
   ir_led_switch:'Instruction light',
   ios_sting_3:'Loading...',
   ios_sting_4:'Seeting Up...',
   ios_sting_5:'Indicator Settings',
   ir_setting:'Remote settings',
   brand_list:'Brand list',
   set_top_box_list:'Set-top Box List',
   ir_add_ic_title_name:'Add remote',
   ir_matching_controller:'Pair remote',
   ir_study_controller_title:'Duplicate remote',
   ir_matching_success:'Finished',
   ir_device_customer:'Customize remote',
   ir_study_add_btn_text:'Add key',
   ir_toast_version:'Master remote control version:',
   agreement_title:"User Agreement",
   policy_title:"Privacy Policy",
   A03_greement_url:require('../Resources/en_a03_agreement.html'),
   A03_policy_url:require('../Resources/en_a03_policy.html'),
   B01_greement_url:require('../Resources/en_b01_agreement.html'),
   B01_policy_url:require('../Resources/en_b01_policy.html'),
   V2_greement_url:require('../Resources/en_remote_v2_agreement.html'),
   V2_policy_url:require('../Resources/en_remote_v2_policy.html'),
   ir_toast_key_read_timeout:'Timed out, please try again',
   ir_toast_key_send_failed:'Sorry, failed to send',
   ir_toast_key_read_other_error:'An error occurred, please try again',
   ir_toast_get_data_failed:'Failed to obtain data, please keep network connected',
   ir_device_offline:'(Device off-line)',
   ir_device_share:'(Share Device)',
   ir_search_list:'Search List',
   ir_not_learn_text:'Air conditioning has no learning function',
   match_first_control_text:'The first remote controller has come to the front',
   match_last_control_text:'To the last remote control',
   match_remoter_press_text:'Press the same button on the remote control center',
   sence_temp_text:'Temperature',
   sence_mode_text:'Model',
   sence_speed_text:'Wind speed',
   ir_cancel:'Cancel',
   ir_confirm:'OK',
   ir_controller_edit_key_name_title:'Button name',
   ir_input_placeholder_text:'Please enter button name',
   edit_save_failed_no_keys:'No button learned',
   ir_controller_others_already_studied:'Already learned',
   ir_gateWay_list:'Gateway list',
   ir_device_type_no_learn:'This type has no learning function',
   ir_delete:'delete',
   ir_delete_device_text:'Are you sure you want to delete the device?',
   list_select_area:'Select region',
   customer_fun:'custom',
   main_add_desc:'Follow the instructions, and control through a few simple trials',
   ir_main_copy_desc:'Duplicate every command on the buttons of the remote to control',
  },
  "zh-tw":{
    string_is_loading:"Loading…",
    setting:"setting",
    featureSetting:"Shortcut settings",
    commonSetting:"Common settings",
    deviceName:"Device name",
    locationManagement:"Locations",
    shareDevice:"Share device",
    feedback:"feedback",
    ifttt:"Automation",
    firmwareUpgrate:"Check for firmware updates",
    moreSetting:"Additional settings",
    addToDesktop:"Add to Home screen",
    resetDevice:"Remove device",
    licenseAndPolicy:"User Agreement & Privacy Policy",
    ir_main_copy:'Duplicate remote',
    ir_main_add:'Add remote',
    ir_device_type_tv_text:'TV',
    ir_device_type_box_text:'TV Box',
    ir_device_type_air_conditioner_text:'Air conditioner',
    ir_device_type_fan_text:'Fan',
    ir_device_type_set_top_box_text:'Set-top box',
    ir_device_type_purifier_text:'Set-top box',
    ir_device_type_dvd_text:'DVD player',
    ir_device_type_iptv_box_text:'IPTV set-top box',
    ir_device_type_projector_text:'Projector',
    ir_device_type_lamp:'Smart lamp',
    ir_device_type_mi_controller:'Mi Remote',
    ir_device_type_camera:'Camera',
    ir_device_type_amplifier:'Speaker',
    ir_device_type_water_heater:'Water heater',
    ir_device_type_water_unknown:'Mi Home general devices',
    ir_device_type_unknown:'Customize',
    get_way_choose_tips_title:'Please select one IR gateway to control device',
    ir_controller_power_text:'Switch',
    ir_controller_power_on_text:'On',
    ir_controller_power_off_text:'Of',
    ir_controller_mode_text:'Mode',
    ir_controller_sleep_text:'Sleep',
    ir_controller_temp_up_text:'Temperature+',
    ir_controller_temp_down_text:'Temperature-',
    ir_controller_heating_text:'Heating',
    ir_controller_cool_text:'Cooling',
    ir_controller_temp_text:'Adjust',
    ir_controller_comfort_text:'Other buttons',
    wind_speed:'Wind speed',
    wind_speed_auto:'Auto',
    ir_wind_low:'Low',
    ir_wind_mid:'Medium',
    ir_wind_high:'High',
    ac_mode_dry:'Dehumidifying',
    ac_mode_fan:'Venting',
    timer:'Timer',
    wind_sweep:'Swing',
    wind_speed:'Wind speed',
    wind_direct:'Wind direction',
    ir_controller_wind_class_text:'Wind type',
    extra_key_text:'Extension',
    ir_controller_back_text:'Back',
    match_ac_power:'Power',
    search_device:'Search brand',
    search_keyword_text:'Search keyword',
    get_way_choose_tips_title:'Please select one IR gateway to control device',
    ir_match_set_top_box:'Select mobile carrier',
    ir_match_location_format:'Location: ',
    ir_add_ic_description:'Device needs time to respond\nPlease give it a few minutes',
    ir_confirm_button_description_font:'Press remote button toward ',
    ir_confirm_button_description_after:'Press remote button toward ',
    ir_confirm_button_confirm:'Then confirm if',
    ir_confirm_button_response:'s responds',
    ir_add_ic_test_btn_num:'Test buttons',
    ir_single_match_failed:'Pairing failed, please try ',
    extra_key_text:'Extension',
    ir_take_look:'Take a look',
    ir_take_look_desc:'No IR gateway available',
    ir_trun_off_air:'Turn off AC',
    ir_trun_on_air:'Turn on AC',
    ir_trunon_air_special:'Turn on AC and set to designated status',
    device_is_response:'Did the device respond?',
    match_ok_button:'Yes',
    match_cancel_button:'No',
    ir_led_switch:'Instruction light',
    ios_sting_3:'Loading...',
    ios_sting_4:'Seeting Up...',
    ios_sting_5:'Indicator Settings',
    ir_setting:'Remote settings',
    brand_list:'Brand list',
    set_top_box_list:'Set-top Box List',
    ir_add_ic_title_name:'Add remote',
    ir_matching_controller:'Pair remote',
    ir_study_controller_title:'Duplicate remote',
    ir_matching_success:'Finished',
    ir_device_customer:'Customize remote',
    ir_study_add_btn_text:'Add key',
    ir_toast_version:'Master remote control version:',
    agreement_title:"User Agreement",
    policy_title:"Privacy Policy",
    A03_greement_url:require('../Resources/en_a03_agreement.html'),
    A03_policy_url:require('../Resources/en_a03_policy.html'),
    B01_greement_url:require('../Resources/en_b01_agreement.html'),
    B01_policy_url:require('../Resources/en_b01_policy.html'),
    V2_greement_url:require('../Resources/en_remote_v2_agreement.html'),
    V2_policy_url:require('../Resources/en_remote_v2_policy.html'),
    ir_toast_key_read_timeout:'Timed out, please try again',
    ir_toast_key_send_failed:'Sorry, failed to send',
    ir_toast_key_read_other_error:'An error occurred, please try again',
    ir_toast_get_data_failed:'Failed to obtain data, please keep network connected',
    ir_device_offline:'(Device off-line)',
    ir_device_share:'(Share Device)',
    ir_search_list:'Search List',
    ir_not_learn_text:'Air conditioning has no learning function',
    match_first_control_text:'The first remote controller has come to the front',
    match_last_control_text:'To the last remote control',
    match_remoter_press_text:'Press the same button on the remote control center',
    sence_temp_text:'Temperature',
    sence_mode_text:'Model',
    sence_speed_text:'Wind speed',
    ir_cancel:'Cancel',
    ir_confirm:'OK',
    ir_controller_edit_key_name_title:'Button name',
    ir_input_placeholder_text:'Please enter button name',
    edit_save_failed_no_keys:'No button learned',
    ir_controller_others_already_studied:'Already learned',
    ir_gateWay_list:'Gateway list',
    ir_device_type_no_learn:'This type has no learning function',
    ir_delete:'delete',
    ir_delete_device_text:'Are you sure you want to delete the device?',
    list_select_area:'Select region',
    customer_fun:'custom',
    main_add_desc:'Follow the instructions, and control through a few simple trials',
    ir_main_copy_desc:'Duplicate every command on the buttons of the remote to control',
  },
  "krea":{
     string_is_loading:"Loading…",
     setting:"setting",
     featureSetting:"Shortcut settings",
     commonSetting:"Common settings",
     deviceName:"Device name",
     feedback:"feedback",
     locationManagement:"Locations",
     shareDevice:"Share device",
     ifttt:"Automation",
     firmwareUpgrate:"Check for firmware updates",
     moreSetting:"Additional settings",
     addToDesktop:"Add to Home screen",
     resetDevice:"Remove device",
     licenseAndPolicy:"User Agreement & Privacy Policy",
     ir_main_copy:'Duplicate remote',
     ir_main_add:'Add remote',
     ir_device_type_tv_text:'TV',
     ir_device_type_box_text:'TV Box',
     ir_device_type_air_conditioner_text:'Air conditioner',
     ir_device_type_fan_text:'Fan',
     ir_device_type_set_top_box_text:'Set-top box',
     ir_device_type_purifier_text:'Set-top box',
     ir_device_type_dvd_text:'DVD player',
     ir_device_type_iptv_box_text:'IPTV set-top box',
     ir_device_type_projector_text:'Projector',
     ir_device_type_lamp:'Smart lamp',
     ir_device_type_mi_controller:'Mi Remote',
     ir_device_type_camera:'Camera',
     ir_device_type_amplifier:'Speaker',
     ir_device_type_water_heater:'Water heater',
     ir_device_type_water_unknown:'Mi Home general devices',
     ir_device_type_unknown:'Customize',
     get_way_choose_tips_title:'Please select one IR gateway to control device',
     ir_controller_power_text:'Switch',
     ir_controller_power_on_text:'On',
     ir_controller_power_off_text:'Of',
     ir_controller_mode_text:'Mode',
     ir_controller_sleep_text:'Sleep',
     ir_controller_temp_up_text:'Temperature+',
     ir_controller_temp_down_text:'Temperature-',
     ir_controller_heating_text:'Heating',
     ir_controller_cool_text:'Cooling',
     ir_controller_temp_text:'Adjust',
     ir_controller_comfort_text:'Other buttons',
     wind_speed:'Wind speed',
     wind_speed_auto:'Auto',
     ir_wind_low:'Low',
     ir_wind_mid:'Medium',
     ir_wind_high:'High',
     ac_mode_dry:'Dehumidifying',
     ac_mode_fan:'Venting',
     timer:'Timer',
     wind_sweep:'Swing',
     wind_speed:'Wind speed',
     wind_direct:'Wind direction',
     ir_controller_wind_class_text:'Wind type',
     extra_key_text:'Extension',
     ir_controller_back_text:'Back',
     match_ac_power:'Power',
     search_device:'Search brand',
     search_keyword_text:'Search keyword',
     get_way_choose_tips_title:'Please select one IR gateway to control device',
     ir_match_set_top_box:'Select mobile carrier',
     ir_match_location_format:'Location: ',
     ir_add_ic_description:'Device needs time to respond\nPlease give it a few minutes',
     ir_confirm_button_description_font:'Press remote button toward ',
     ir_confirm_button_description_after:'Press remote button toward ',
     ir_confirm_button_confirm:'Then confirm if',
     ir_confirm_button_response:'s responds',
     ir_add_ic_test_btn_num:'Test buttons',
     ir_single_match_failed:'Pairing failed, please try ',
     extra_key_text:'Extension',
     ir_take_look:'Take a look',
     ir_take_look_desc:'No IR gateway available',
     ir_trun_off_air:'Turn off AC',
     ir_trun_on_air:'Turn on AC',
     ir_trunon_air_special:'Turn on AC and set to designated status',
     device_is_response:'Did the device respond?',
     match_ok_button:'Yes',
     match_cancel_button:'No',
     ir_led_switch:'Instruction light',
     ios_sting_3:'Loading...',
     ios_sting_4:'Seeting Up...',
     ios_sting_5:'Indicator Settings',
     ir_setting:'Remote settings',
     brand_list:'Brand list',
     set_top_box_list:'Set-top Box List',
     ir_add_ic_title_name:'Add remote',
     ir_matching_controller:'Pair remote',
     ir_study_controller_title:'Duplicate remote',
     ir_matching_success:'Finished',
     ir_device_customer:'Customize remote',
     ir_study_add_btn_text:'Add key',
     ir_toast_version:'Master remote control version:',
     agreement_title:"User Agreement",
     policy_title:"Privacy Policy",
     A03_greement_url:require('../Resources/en_a03_agreement.html'),
     A03_policy_url:require('../Resources/en_a03_policy.html'),
     B01_greement_url:require('../Resources/en_b01_agreement.html'),
     B01_policy_url:require('../Resources/en_b01_policy.html'),
     V2_greement_url:require('../Resources/en_remote_v2_agreement.html'),
     V2_policy_url:require('../Resources/en_remote_v2_policy.html'),
     ir_toast_key_read_timeout:'Timed out, please try again',
     ir_toast_key_send_failed:'Sorry, failed to send',
     ir_toast_key_read_other_error:'An error occurred, please try again',
     ir_toast_get_data_failed:'Failed to obtain data, please keep network connected',
     ir_device_offline:'(Device off-line)',
     ir_device_share:'(Share Device)',
     ir_search_list:'Search List',
     ir_not_learn_text:'Air conditioning has no learning function',
     match_first_control_text:'The first remote controller has come to the front',
     match_last_control_text:'To the last remote control',
     match_remoter_press_text:'Press the same button on the remote control center',
     sence_temp_text:'Temperature',
     sence_mode_text:'Model',
     sence_speed_text:'Wind speed',
     ir_cancel:'Cancel',
     ir_confirm:'OK',
     ir_controller_edit_key_name_title:'Button name',
     ir_input_placeholder_text:'Please enter button name',
     edit_save_failed_no_keys:'No button learned',
     ir_controller_others_already_studied:'Already learned',
     ir_gateWay_list:'Gateway list',
     ir_device_type_no_learn:'This type has no learning function',
     ir_delete:'delete',
     ir_delete_device_text:'Are you sure you want to delete the device?',
     list_select_area:'Select region',
     customer_fun:'custom',
     main_add_desc:'Follow the instructions, and control through a few simple trials',
     ir_main_copy_desc:'Duplicate every command on the buttons of the remote to control',
  }
};
export const LocalizedStrings = new MHLocalizedStrings(strings);

export function getString(key, obj = null) {
  if (obj) {
    return new IntlMessageFormat(LocalizedStrings[key], LocalizedStrings.language).format(obj);
  } else {
    return LocalizedStrings[key];
  }
}
