import MHLocalizedStrings from '../CommonModules/LocalizedStrings';
import IntlMessageFormat from 'intl-messageformat';
import 'intl';
import 'intl/locale-data/jsonp/en.js';
import 'intl/locale-data/jsonp/zh-Hans.js';
import 'intl/locale-data/jsonp/zh-Hant.js';
import 'intl/locale-data/jsonp/ko-KR.js';
export const strings = {
  "en":{
    setting:"setting",
    featureSetting:"Shortcut settings",
    commonSetting:"Common settings",
    deviceName:"Device name",
    locationManagement:"Locations",
    shareDevice:"Share device",
    ifttt:"Automation",
    firmwareUpgrate:"Check for firmware updates",
    moreSetting:"Additional settings",
    addToDesktop:"Add to Home screen",
    resetDevice:"Remove device",
    licenseAndPolicy:"User Agreement & Privacy Policy",
   feedback:"feedback",
   app_name:"Smart Plug",
   hello_world:"Hello world!",
   gateway_magnet_location_updating:"Updating...",
   minute:"min",
   hour:"hr",
   day:"days",
   later:"ago",
   plug_timer_yesterday:"Yesterday",
   plug_timer_after_tommorrow:"day after tomorrow",
   plug_timer_month_day:"%1$s/%2$s",
   plug_switch:"On/Off",
   plug_timer:"Timer",
   plug_count_down_timer:"Countdown",
   time_line_start:"00:00",
   time_line_end:"24:00",
   power_on:"Plug power is on",
   power_off:"Plug power is off",
   usb_on:"Plug USB is on",
   usb_off:"Plug USB is off",
   close:" off",
   open:" on",
   count_down_msg_minute:"min later",
   count_down_msg_hour_minute:"%2$s hours %3$s minutes later%1$s",
   count_down_msg_hour:"%2$s hours later %1$s",
   count_down_msg_day:"%2$s days %3$s hours %4$s minutes later %1$s",
   ok:"OK",
   title_timer_power:"Plug Power Timer",
   title_timer_usb:"Plug USB Timer",
   title_count_down_timer_power:"Plug Power Countdown",
   title_count_down_timer_usb:"Plug USB Countdown",
   set_timer_conflict:"The time you’re setting conflicts with a previously set time. Are you sure you want to do this?",
   i_know:"Got it",
   set_failed:"Could not complete set up.",
   get_failed:"Could not complete update.",
   delete_failed:"Could not delete.",
   temp_high_alert_title:"Plug has overheated. Please figure out why before using again.",
   temp_high_alert_msg1:"1. \u0020Equipment may be using too much power (over its max limit).",
   temp_high_alert_msg2:"2.\u0020It’s possible that the AC jack connected to the smart plug ",
   temp_high_alert_msg5:"\u0020\u0020\u0020may be loose and/or rusted.",
   temp_high_alert_msg3:"3.\u0020The plugs on the equipment that’s using power may be old and/or rusted.",
   temp_high_alert_msg4:"4.\u0020The ambient temperature may be too high.",
   settings_sending_notification:"Timed reminders",
   settings_sending_notification_tips:"Send a message to notify you when the plug is scheduled to turn on.",
   settings_general:"General settings",
   about:"About",
   more_function:"More Functions",
   noti_overheat_title:"Your plug is overheating.",
   noti_overheat_msg:"Your plug is overheating. Please let it rest for a bit.",
   noti_device_title:"Your plug %1$s is already %2$s.",
   noti_device_title_power:"Power",
   noti_device_title_usb:"USB",
   noti_device_title_open:"Turn on",
   noti_device_title_close:"Turn off",
   one_minute:"1 minute",
   three_minute:"3 minutes",
   five_minute:"5 minutes",
   ten_minute:"10 minutes",
   twenty_minute:"20 minutes",
   forty_minute:"40 minutes",
   sixty_minute:"60 minutes",
   customize_minute:"Custom",
   start:"Start",
   cancel:"Cancel",
   stop:"Stop",
   timer_emtpy:"Timer is set to 0",
   plug_seat_high_temp:"The plug is overheating. ",
   plug_seat_high_temp_tips:"Please figure out why before using again.",
   status_on:"Turned on",
   status_off:"Turned off",
   device_desc_220v:"220V Plug:",
   device_desc_USB:"USB:",
   max_timer_count_tips:"You cannot add any more timers now. Please delete one from the list before trying again.",
   device_scene:"Automation",
   over_heat_tips:"Plug is overheating, so it has gone into safe mode.",
   wifi_led_name:"Indicator Switch",
   share:"Shared Devices",
   ok1:"OK",
   virtual_dialog_title:"Virtual devices cannot be updated...",
   virtual_dialog_positive:"I’ll take one too!",
   plugseat_v1_keyword:"Smart Plug v1",
   merge_old_timer_data:"Migrating old data...",
   old_timer_upgrade_tips:"Timer Upgrade Tips",
   old_timer_upgrade_msg:"After the plug has been upgraded, timers you’ve set in the APP can be stored in the plug. After setup is complete, you can continue to set timers, even when you’re not connected to a WLAN.",
   upgrade:"Upgrade",
   upgrading:"Updating",
   cancel_upgrading:"Cancel upgrade",
   continue_upgrading:"Continue upgrade",
   cancel_upgrading_tips:"Cancel upgrade?",
   cancel_upgrading_msg:"Canceling the upgrade will delete your current timer settings, and you will be unable to set the timer unless you are connected to WLAN.",
   upgrade_suc:"Upgrade successful.",
   upgrade_fail:"Couldn’t upgrade.",
   retry:"Try again",
   disclaim_title:"Terms and Conditions",
   disclaim_dialog_title:"Terms and Conditions",
   disclaim_content:"I’ve already read the “Smart Plug Terms and Conditions”",
   plug_disclaimer_detail_1:"Using the Smart Plug (any version) with this app is considered voluntary acceptance of these terms.",
   plug_disclaimer_detail_2:"We cannot guarantee that plug timers, remote controls, device links, etc. will function completely normally. We do not recommend using them in places where it may be a safety hazard.",
   plug_disclaimer_detail_3:"When you turn on the “Plug blackout memory” function, after power returns, the plug will resume whatever status it had before the blackout, i.e. if it was off before the blackout, it will remain off; if it was on before the blackout, it will turn back on. Therefore, we do not recommend using it in places where it may be a safety hazard.",
   plug_disclaimer_detail_4:"The company does not assume any responsibility for the inability of the smart plug to function properly if caused by factors including but not limited to hacker attacks, network outages, network delays, equipment that is offline, etc. However, we will do our best to reduce any resultant loss(es) by and/or impact on the user.",
   plug_disclaimer_detail_5:"The company shall not be liable for any losses caused by improper use of this product.",
   agree_and_continue:"Agree and Continue",
   feedback:"Help",
   tips_share_read_only:"Please adjust permissions and try again.",
   string_look_history_data:"View More",
   string_now_all_power:"Current Power",
   string_power_data:"Power Statistics",
   string_today_power_data:"Daily Power Use (kWh)",
   string_no_power_data:"No Power Info",
   string_month_power_data:"Monthly Power Usage",
   string_yesterday_power_data:"Power used yesterday",
   string_today_open_time:"Today’s Usage (Time)",
   string_today_switch_count:"(On/Off) Switches today",
   string_du:"kWh",
   string_shi:"hours",
   string_fen:"minutes",
   string_ci:"times",
   string_month_data:"Monthly Power Details",
   string_week_data:"Weekly Power Details",
   string_day_data:"Daily Power Details",
   string_month:"Month",
   string_week:"Week",
   string_day:"Day",
   string_power_du_data:"Power Consumption (kWh)",
   string_use_time:"Duration of Use (hrs:min)",
   string_is_loading:"Loading…",
   string_1:"Please be careful. Your device is overloaded.",
   string_2:"Plug is overheating and has been turned off.",
   string_3:"The plug is too hot. Please try to figure out why.",
   string_4:"We found a new version of the firmware for you. You can upgrade now.",
   string_5:"Yesterday",
   string_6:"Today",
   string_7:"Last Week",
   string_8:"This Week",
   string_9:"Last Month",
   string_10:"This Month",
   string_11:"M Month",
   string_12:"Turned on 220V plug",
   string_13:"Turned off 220V plug",
   string_14:"Turned on USB",
   string_15:"Turned off USB",
   ios_sting_1:"I’ve already read it.",
   ios_sting_2:"“Smart Plug Terms and Conditions”",
   ios_sting_3:"Loading ...",
   ios_sting_4:"Setting up...",
   ios_sting_5:"Indicator Settings",
   ios_sting_6:"Setting up",
   ios_sting_7:"Feedback",
  },
  "zh":{
    setting:"设置",
    featureSetting:"功能设置",
    commonSetting:"通用设置",
    deviceName:"设备名称",
    locationManagement:"位置管理",
    shareDevice:"设备共享",
    ifttt:"智能",
    firmwareUpgrate:"检查固件升级",
    moreSetting:"更多设置",
    addToDesktop:"添加到桌面",
    resetDevice:"删除设备",
    licenseAndPolicy:"使用条款和隐私政策",
   feedback:"反馈",
   app_name:"智能插座",
   hello_world:"Hello world!",
   gateway_magnet_location_updating:"更新中...",
   minute:"分钟",
   hour:"小时",
   day:"天",
   later:"后",
   plug_timer_yesterday:"昨天",
   plug_timer_after_tommorrow:"后天",
   plug_timer_month_day:"%1$s月%2$s日",
   plug_switch:"开关",
   plug_timer:"定时",
   plug_count_down_timer:"倒计时",
   time_line_start:"00:00",
   time_line_end:"24:00",
   power_on:"插座电源已开启",
   power_off:"插座电源已关闭",
   usb_on:"插座USB已开启",
   usb_off:"插座USB已关闭",
   close:"关闭",
   open:"开启",
   count_down_msg_minute:"分钟后",
   count_down_msg_hour_minute:"%2$s小时%3$s分钟后%1$s",
   count_down_msg_hour:"%2$s小时后%1$s",
   count_down_msg_day:"%2$s天%3$s小时%4$s分钟后%1$s",
   ok:"确定",
   title_timer_power:"插座电源定时",
   title_timer_usb:"插座USB定时",
   title_count_down_timer_power:"插座电源倒计时",
   title_count_down_timer_usb:"插座USB倒计时",
   set_timer_conflict:"您当前设置的时间与您以前设置的定时时间有冲突，是否只执行当前的设置？",
   i_know:"我知道了",
   set_failed:"设置失败",
   get_failed:"更新失败",
   delete_failed:"删除失败",
   temp_high_alert_title:"插座温度过高，请检查原因后使用！",
   temp_high_alert_msg1:"1.\u0020用电设备功率可能超过最大限值",
   temp_high_alert_msg2:"2.\u0020与智能插座插头连接的交流电插孔内部可能存在",
   temp_high_alert_msg5:"\u0020\u0020\u0020生锈松动等情况",
   temp_high_alert_msg3:"3.\u0020用电设备的插头可能存在老化生锈等情况",
   temp_high_alert_msg4:"4.\u0020智能插座所处环境的温度可能过高",
   settings_sending_notification:"定时执行提醒",
   settings_sending_notification_tips:"插座定时执行时发送消息通知您",
   settings_general:"通用设置",
   about:"关于",
   more_function:"更多功能",
   noti_overheat_title:"您的插座过热!",
   noti_overheat_msg:"您的插座过热，请及时处理",
   noti_device_title:"您的插座%1$s已经%2$s",
   noti_device_title_power:"电源",
   noti_device_title_usb:"USB",
   noti_device_title_open:"开启",
   noti_device_title_close:"关闭",
   one_minute:"1分钟",
   three_minute:"3分钟",
   five_minute:"5分钟",
   ten_minute:"10分钟",
   twenty_minute:"20分钟",
   forty_minute:"40分钟",
   sixty_minute:"60分钟",
   customize_minute:"自定义",
   start:"启动",
   cancel:"取消",
   stop:"停止",
   timer_emtpy:"定时为空",
   plug_seat_high_temp:"插座温度过高",
   plug_seat_high_temp_tips:"请检查原因后再使用",
   status_on:"已开启",
   status_off:"已关闭",
   device_desc_220v:"220V插座:",
   device_desc_USB:"USB:",
   max_timer_count_tips:"您设置的定时数量已达上限，如需新的定时设置请删除以前的定时操作！",
   device_scene:"自动化",
   over_heat_tips:"插座过热, 已开启安全保护",
   wifi_led_name:"指示灯开关",
   share:"分享设备",
   ok1:"好吧",
   virtual_dialog_title:"虚拟设备无法进行更多操作...",
   virtual_dialog_positive:"我也来一个！",
   plugseat_v1_keyword:"智能插座v1",
   merge_old_timer_data:"正在迁移旧数据",
   old_timer_upgrade_tips:"定时升级提示",
   old_timer_upgrade_msg:"插座升级后可以将APP设定的定时消息存储在插座中，设置成功后在没有WLAN连接时也可以继续执行设置成功的定时操作",
   upgrade:"升级",
   upgrading:"升级中...",
   cancel_upgrading:"取消升级",
   continue_upgrading:"继续升级",
   cancel_upgrading_tips:"确定取消升级么？",
   cancel_upgrading_msg:"取消升级操作后将有可能丢失您以前设置的定时数据，并且在WLAN无连接时将无法执行设置成功的定时操作",
   upgrade_suc:"升级成功",
   upgrade_fail:"升级失败",
   retry:"重试",
   disclaim_title:"使用须知",
   disclaim_dialog_title:"使用须知",
   disclaim_content:"我已阅读《智能插座使用须知》",
   plug_disclaimer_detail_1:"凡以任何方式在app中使用智能插座（所有版本）均被视为自愿接受本须知。",
   plug_disclaimer_detail_2:"插座的定时、倒计时、远程控制、设备联动等功能无法保证100%正确执行，不建议应用在会造成安全隐患的场景中。",
   plug_disclaimer_detail_3:"插座的断电记忆功能开启后，停电前如果插座处于开启状态，来电后仍保持开启状态，因此不建议应用在会造成安全隐患的场景中。",
   plug_disclaimer_detail_4:"在包括但不限于黑客攻击、网络中断、网络延时、设备离线等原因造成的插座未正确执行的情况下，本公司不承担任何责任，但将尽力减少因此给用户造成的损失或影响。",
   plug_disclaimer_detail_5:"因不当使用本产品而导致的任何损失，本公司亦不承担任何法律责任。",
   agree_and_continue:"同意并继续",
   feedback:"使用帮助",
   tips_share_read_only:"当前权限下不支持控制操作",
   string_look_history_data:"查看更多数据",
   string_now_all_power:"当前功率",
   string_power_data:"电量统计",
   string_today_power_data:"今日用电(度)",
   string_no_power_data:"无用电信息",
   string_month_power_data:"本月用电",
   string_yesterday_power_data:"昨日用电",
   string_today_open_time:"今日开启时长",
   string_today_switch_count:"今日开关次数",
   string_du:"度",
   string_shi:"时",
   string_fen:"分",
   string_ci:"次",
   string_month_data:"月用电详情",
   string_week_data:"周用电详情",
   string_day_data:"日用电详情",
   string_month:"月",
   string_week:"周",
   string_day:"日",
   string_power_du_data:"用电量(度)",
   string_use_time:"使用时长(时:分)",
   string_is_loading:"加载中…",
   string_1:"请注意,当前设备负载电流过大",
   string_2:"插座过热,已关闭插座电源",
   string_3:"插座温度过高，请检查原因",
   string_4:"主人，发现新的固件可以升级哦～",
   string_5:"昨日",
   string_6:"今日",
   string_7:"上周",
   string_8:"本周",
   string_9:"上月",
   string_10:"本月",
   string_11:"M月",
   string_12:"开启了220V插孔开关",
   string_13:"关闭了220V插孔开关",
   string_14:"开启了USB开关",
   string_15:"关闭了USB开关",
   ios_sting_1:"我已阅读",
   ios_sting_2:"《智能插座使用须知》",
   ios_sting_3:"加载中...",
   ios_sting_4:"设置中...",
   ios_sting_5:"指示灯设置",
   ios_sting_6:"正在设置",
   ios_sting_7:"反馈",
  },
  'zh-tw': {
    NUM_PHOTOS: 'You have {numPhotos, plural, ' +
      '=0 {no photos.}' +
      '=1 {one photo.}' +
      'other {# photos.}}',
    setting: '設置',
    featureSetting: '功能設定',
    commonSetting: '一般設定',
    deviceName: '裝置名稱',
    locationManagement: '位置管理',
    shareDevice: '裝置共用',
    ifttt: '自動化',
    firmwareUpgrate: '檢查韌體更新',
    moreSetting: '更多設定',
    addToDesktop: '新增到桌面',
    resetDevice: '重置裝置',
    licenseAndPolicy: '用戶協議和隱私政策',
  },
  'zh-hk': {
    NUM_PHOTOS: 'You have {numPhotos, plural, ' +
      '=0 {no photos.}' +
      '=1 {one photo.}' +
      'other {# photos.}}',
    setting: '設置',
    featureSetting: 'feature setting',
    commonSetting: '一般設定',
    deviceName: '裝置名稱',
    locationManagement: '位置管理',
    shareDevice: '裝置共用',
    ifttt: '自動化',
    firmwareUpgrate: '檢查韌體更新',
    moreSetting: '更多設定',
    addToDesktop: '新增到桌面',
    resetDevice: '重置裝置',
    licenseAndPolicy: '用戶協議和隱私政策',
  },
  'ko': {
    NUM_PHOTOS: 'You have {numPhotos, plural, ' +
      '=0 {no photos.}' +
      '=1 {one photo.}' +
      'other {# photos.}}',
    featureSetting: '바로가기 설정',
    commonSetting: '일반 설정',
    deviceName: '기기 이름',
    locationManagement: '위치',
    shareDevice: '기기 공유',
    ifttt: '자동화',
    firmwareUpgrate: '펌웨어 업데이트 확인',
    moreSetting: '추가 설정',
    addToDesktop: '홈 화면에 추가',
    resetDevice: '기기 초기화',
    licenseAndPolicy: '이용 약관 & 개인 정보 보호 정책',
  },
};
export const LocalizedStrings = new MHLocalizedStrings(strings);

export function getString(key, obj = null) {
  if (obj) {
    return new IntlMessageFormat(LocalizedStrings[key], LocalizedStrings.language).format(obj);
  } else {
    return LocalizedStrings[key];
  }
}
